name: BOM check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install deps (for script)
        run: npm ci --prefer-offline --no-audit --no-fund
      - name: Check for BOM in JSON files
        run: node scripts/remove-bom.js --check
