name: CI — build portfolio-mixed

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Install & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build portfolio-mixed workspace
        run: npm run build:mixed

      - name: Upload build output (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-mixed-next
          path: apps/portfolio-mixed/.next
